// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double randomNumber;
		int countBigger=0;
		int countSmaller=0;
		int i;
		for (i=0;i<n;i++) {
			randomNumber=Math.random();
			if (randomNumber<0.5)
			{
				countSmaller=countSmaller+1;
			}
			else
			{
				countBigger=countBigger+1;
			}
		}
		System.out.println(">0.5: "+countBigger);
		System.out.println("<=0.5: "+countSmaller);
		if (countSmaller!=0)
		{
			System.out.println("Ratio: "+((double)countBigger/(double)countSmaller));
		}
	}
}
